### ISSUE TITLE
touch fails because directory is missing

### ISSUE THREAD

**Issue by pkruithof** [cleentfaar/slack-cli#5]
The first time the config file is created, the `.slack-cli` directory does not yet exist, which raises a warning:

```
PHP Warning:  touch(): Unable to create file /root/.slack-cli/config.json because No such file or directory in phar:///usr/local/bin/slack/src/CL/SlackCli/Command/AbstractCommand.php on line 99
```

Furthermore, the config is created on every command, even when not using it. This seems unnecessary.

**Comment by cleentfaar** [comment]
This should be fixed now in the latest release (`0.16.1`), thanks for reporting!
